"""is_new included in user

Revision ID: 8dd9313a162e
Revises: 0ac81c902950
Create Date: 2025-08-02 11:27:21.784749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8dd9313a162e'
down_revision: Union[str, Sequence[str], None] = '0ac81c902950'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restaurant_orders')
    op.add_column('users', sa.Column('is_new', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_new')
    op.create_table('restaurant_orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('restaurant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('order_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('menu_item', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('weather_info', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('external_factors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('restaurant_orders_restaurant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('restaurant_orders_pkey'))
    )
    # ### end Alembic commands ###
