"""Updated Models

Revision ID: 998ed4da5387
Revises: 63ea09e615a6
Create Date: 2025-07-27 19:01:03.052011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '998ed4da5387'
down_revision: Union[str, Sequence[str], None] = '63ea09e615a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restaurant_orders')
    op.add_column('restaurants', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.add_column('restaurants', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('users', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.add_column('users', sa.Column('force_password_reset', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'force_password_reset')
    op.drop_column('users', 'tenant_id')
    op.drop_column('users', 'created_at')
    op.drop_column('restaurants', 'is_active')
    op.drop_column('restaurants', 'tenant_id')
    op.create_table('restaurant_orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('restaurant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('order_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('menu_item', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('weather_info', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('external_factors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('restaurant_orders_restaurant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('restaurant_orders_pkey'))
    )
    # ### end Alembic commands ###
